apiVersion: 1

datasources:
  - name: Prometheus # Это имя будет отображаться в списке источников данных
    type: prometheus # Тип источника данных
    access: proxy # Рекомендуемый режим доступа
    orgId: 1 # ID организации (1 - это организация по умолчанию)
    url: http://prometheus:9090 # КЛЮЧЕВОЙ МОМЕНТ: Обращение по имени сервиса из docker-compose
    editable: false # Запрещает изменять или удалять этот источник через веб-интерфейс